name: bar_gym_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
# state management
  provider:
  stacked:
  stacked_services:
# components
  flutter_speed_dial:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  stacked_generator:

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

